vich_uploader:
    db_driver: orm

    mappings:
        participant_file:
            uri_prefix: /uploads/participants
            upload_destination: '%kernel.project_dir%/public/uploads/participants'

















    #mappings:
    #    image_recette:
    #        uri_prefix: /uploads/recettes
    #        upload_destination: '%kernel.project_dir%/public/uploads/recettes'